"""Elliptic-curve guided search for rational-distance solutions.

Layer 2 of the search strategy: given the parametric seeds found by
brute force, this module extends them along the rational orbit of the
associated quartic elliptic curve to find additional solutions that
lie outside the brute-force range.

Mathematical background
-----------------------
For a primitive Pythagorean triple (p, q, r) with p²+q²=r², consider
the point P=(x,y) = (kp/r, kq/r).  Then:

    dA = k  (always rational for rational k)
    dB² = k² - 2k(p/r) + 1
    dD² = k² - 2k(q/r) + 1
    dC² = dB² + dD² - dA²  (parallelogram law: dA²+dC²=dB²+dD²)

Parametrize the conic dB²=k²-2kp/r+1 via slope t through (k,dB)=(0,1):

    k(t) = 2(t + p/r) / (1 - t²)
    dB(t) = (1 + t² + 2tp/r) / (1 - t²)

Substituting into dD and letting E = r·dD·(1-t²) gives the quartic:

    E² = F(t)  where
    F(t) = r²t⁴ + 4qrt³ + (2r²+4pq)t² + 4r(2p-q)t + (4p²-4pq+r²)

Rational points on this curve (hyperelliptic genus-1 curve over ℚ) form
a group under the chord-tangent law.  Starting from a *seed* — a rational
point discovered by brute force — new rational points are generated by
applying tangent and secant steps.  Each new rational t yields a new
rational k (and thus a new candidate point), which is then checked for
the full 3- or 4-vertex rationality condition.
"""

from __future__ import annotations

from fractions import Fraction
from math import gcd, isqrt
from typing import Optional

from rational_distance.math_utils import primitive_pythagorean_triples, rational_sqrt
from rational_distance.square import RationalPoint, canonical_xy, make_point


# ---------------------------------------------------------------------------
# Quartic elliptic curve for one Pythagorean triple
# ---------------------------------------------------------------------------

class QuarticEC:
    """Quartic elliptic curve  E² = F(t)  associated with triple (p, q, r).

    Coefficients (all integers, since p,q,r ∈ ℤ):
        c4 = r²
        c3 = 4qr
        c2 = 2r² + 4pq
        c1 = 4r(2p - q)
        c0 = 4p² - 4pq + r²
    """

    def __init__(self, p: int, q: int, r: int) -> None:
        self.p = p
        self.q = q
        self.r = r
        self.c4 = r * r
        self.c3 = 4 * q * r
        self.c2 = 2 * r * r + 4 * p * q
        self.c1 = 4 * r * (2 * p - q)
        self.c0 = 4 * p * p - 4 * p * q + r * r

    def F(self, t: Fraction) -> Fraction:
        """Evaluate the quartic polynomial F(t)."""
        return (self.c4 * t**4 + self.c3 * t**3
                + self.c2 * t**2 + self.c1 * t + self.c0)

    def on_curve(self, t: Fraction, E: Fraction) -> bool:
        """Return True iff (t, E) satisfies E² = F(t)."""
        return E * E == self.F(t)

    def k_from_t(self, t: Fraction) -> Optional[Fraction]:
        """Convert slope parameter t to scale factor k.

        k(t) = 2(t + p/r) / (1 - t²)

        Returns None when t = ±1 (k = ∞, projective point).
        """
        denom = 1 - t * t
        if denom == 0:
            return None
        return 2 * (t + Fraction(self.p, self.r)) / denom

    def t_from_k_dB(self, k: Fraction, dB: Fraction) -> list[Fraction]:
        """Recover the slope parameter t from (k, dB).

        From the parametrization:  t = (dB·(1-t²) - 1 - t²·...) — but
        the simpler inversion comes from the definition of the slope:
            t = (k - 1 - dB) / k   or   t = (k - 1 + dB) / (-k)
        which simplifies to:
            t = (-1 ± dB) / k  (when k ≠ 0)
        Returns all valid real roots (at most 2).
        """
        if k == 0:
            return []
        return [(-1 + dB) / k, (-1 - dB) / k]

    def E_from_t_dD(self, t: Fraction, dD: Fraction) -> Fraction:
        """Compute E = r·dD·(1-t²) from t and dD."""
        return Fraction(self.r) * dD * (1 - t * t)

    # ------------------------------------------------------------------
    # Chord-tangent arithmetic
    # ------------------------------------------------------------------

    def _tangent_quadratic(
        self, t0: Fraction, E0: Fraction
    ) -> tuple[Fraction, Fraction, Fraction]:
        """Return (A, B, C) of residual quadratic h after removing double root t0.

        The tangent line Y = λ(t-t0)+E0 meets the quartic in (t0,E0) twice
        plus two more points whose t-values are roots of h(t)=At²+Bt+C.

            λ = F'(t0) / (2·E0)
            A = c4
            B = c3 + 2·c4·t0
            C = c2 - λ² + 2·c3·t0 + 3·c4·t0²
        """
        Fp = (4 * self.c4 * t0**3 + 3 * self.c3 * t0**2
              + 2 * self.c2 * t0 + self.c1)
        slope = Fp / (2 * E0)
        A = Fraction(self.c4)
        B = Fraction(self.c3) + 2 * A * t0
        C = Fraction(self.c2) - slope**2 + 2 * Fraction(self.c3) * t0 + 3 * A * t0**2
        return A, B, C

    def _secant_quadratic(
        self,
        t1: Fraction, E1: Fraction,
        t2: Fraction, E2: Fraction,
    ) -> tuple[Fraction, Fraction, Fraction]:
        """Return (A, B, C) of residual quadratic h after removing roots t1, t2.

        The secant line Y = μt+ν meets the quartic in (t1,E1), (t2,E2) plus
        two more points whose t-values are roots of h(t)=At²+Bt+C.

            μ = (E2-E1) / (t2-t1)
            A = c4
            B = c3 + c4·(t1+t2)
            C = c2 - μ² + B·(t1+t2) - c4·t1·t2
        """
        slope = (E2 - E1) / (t2 - t1)
        A = Fraction(self.c4)
        B = Fraction(self.c3) + A * (t1 + t2)
        C = Fraction(self.c2) - slope**2 + B * (t1 + t2) - A * t1 * t2
        return A, B, C

    def _new_t_from_line(
        self,
        A: Fraction, B: Fraction, C: Fraction,
        slope: Fraction, intercept: Fraction,
    ) -> list[tuple[Fraction, Fraction]]:
        """Find rational roots of h(t)=At²+Bt+C and return (t_new, E_new) pairs.

        E_new = slope·t_new + intercept  (from the tangent/secant line).
        Only roots with rational discriminant are returned.
        """
        disc = B * B - 4 * A * C
        sqrt_disc = rational_sqrt(disc)
        if sqrt_disc is None:
            return []
        results = []
        for sign in [1, -1]:
            t_new = (-B + sign * sqrt_disc) / (2 * A)
            E_new = slope * t_new + intercept
            results.append((t_new, E_new))
        return results

    def tangent_points(
        self, t0: Fraction, E0: Fraction
    ) -> list[tuple[Fraction, Fraction]]:
        """Apply the tangent step at (t0, E0).

        Returns new (t, E) pairs on the quartic distinct from (t0, E0).
        """
        A, B, C = self._tangent_quadratic(t0, E0)
        Fp = (4 * self.c4 * t0**3 + 3 * self.c3 * t0**2
              + 2 * self.c2 * t0 + self.c1)
        slope = Fp / (2 * E0)
        intercept = E0 - slope * t0
        pts = self._new_t_from_line(A, B, C, slope, intercept)
        return [(t, E) for t, E in pts if t != t0]

    def secant_points(
        self,
        t1: Fraction, E1: Fraction,
        t2: Fraction, E2: Fraction,
    ) -> list[tuple[Fraction, Fraction]]:
        """Apply the secant step through (t1, E1) and (t2, E2).

        Returns new (t, E) pairs on the quartic distinct from t1 and t2.
        Returns empty list when t1 == t2.
        """
        if t1 == t2:
            return []
        A, B, C = self._secant_quadratic(t1, E1, t2, E2)
        slope = (E2 - E1) / (t2 - t1)
        intercept = E1 - slope * t1
        pts = self._new_t_from_line(A, B, C, slope, intercept)
        return [(t, E) for t, E in pts if t != t1 and t != t2]

    def expand_orbit(
        self,
        seeds: list[tuple[Fraction, Fraction]],
        max_steps: int = 20,
        max_denom: int = 10**18,
    ) -> list[Fraction]:
        """Expand the rational orbit starting from seed points.

        Applies tangent and secant steps up to max_steps iterations.
        Returns a list of rational k values corresponding to found points
        on the quartic, filtered to exclude k=0, k<0, and k=∞.

        Points whose t-denominator exceeds max_denom are skipped to
        prevent runaway fraction growth.
        """
        orbit: dict[Fraction, Fraction] = {}  # t -> E
        for t, E in seeds:
            if abs(t.denominator) <= max_denom:
                orbit[t] = E

        queue = list(orbit.items())
        step = 0

        while queue and step < max_steps:
            step += 1
            new_pts: list[tuple[Fraction, Fraction]] = []

            for t0, E0 in queue:
                # Tangent step
                for t_new, E_new in self.tangent_points(t0, E0):
                    if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                        new_pts.append((t_new, E_new))

            # Secant steps between all pairs in the current frontier
            frontier = list(orbit.items())
            for i in range(len(frontier)):
                for j in range(i + 1, len(frontier)):
                    t1, E1 = frontier[i]
                    t2, E2 = frontier[j]
                    for t_new, E_new in self.secant_points(t1, E1, t2, E2):
                        if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                            new_pts.append((t_new, E_new))
                    # Also try with negated E2 (the other branch of the curve)
                    for t_new, E_new in self.secant_points(t1, E1, t2, -E2):
                        if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                            new_pts.append((t_new, E_new))

            if not new_pts:
                break

            # Deduplicate and add to orbit
            for t_new, E_new in new_pts:
                if t_new not in orbit:
                    orbit[t_new] = E_new
            queue = new_pts

        # Convert t values to k values, filtering out infinite/negative k
        k_values = []
        for t in orbit:
            k = self.k_from_t(t)
            if k is not None and k > 0:
                k_values.append(k)
        return k_values


# ---------------------------------------------------------------------------
# Seed finder: brute-force search for (k, dB, dD) all rational
# ---------------------------------------------------------------------------

def find_seeds_for_triple(
    p: int,
    q: int,
    r: int,
    max_k_num: int,
    max_k_den: int,
    inside_only: bool = False,
) -> list[tuple[Fraction, Fraction, Fraction]]:
    """Find all rational k = a/b ∈ (0, max_k_num/max_k_den] such that
    dB = |P-B| and dD = |P-D| are both rational, where P=(kp/r, kq/r).

    These are seeds for the quartic elliptic curve associated with (p,q,r).

    Returns a list of (k, dB, dD) Fraction triples.  Points on extended
    sides (x=1 or y=1) are excluded by the side-exclusion theorem.
    """
    seeds: list[tuple[Fraction, Fraction, Fraction]] = []

    for b in range(1, max_k_den + 1):
        for a in range(1, max_k_num + 1):
            if gcd(a, b) != 1:
                continue

            # Side exclusion: x = ap/br = 1 iff a*p = b*r; similarly y=1 iff a*q = b*r
            if a * p == b * r or a * q == b * r:
                continue

            # inside_only: require 0 < x < 1 and 0 < y < 1
            if inside_only and (a * p > b * r or a * q > b * r):
                continue

            ar, bp, bq, br = a * r, b * p, b * q, b * r

            # dB² = ((ar-bp)² + bq²) / br² — check numerator is a perfect square
            tB = (ar - bp) ** 2 + bq * bq
            sB = isqrt(tB)
            if sB * sB != tB:
                s1 = sB + 1
                if s1 * s1 != tB:
                    continue
                sB = s1

            # dD² = ((ar-bq)² + bp²) / br² — check numerator is a perfect square
            tD = (ar - bq) ** 2 + bp * bp
            sD = isqrt(tD)
            if sD * sD != tD:
                s1 = sD + 1
                if s1 * s1 != tD:
                    continue
                sD = s1

            k = Fraction(a, b)
            dB = Fraction(sB, br)
            dD = Fraction(sD, br)
            seeds.append((k, dB, dD))

    return seeds


# ---------------------------------------------------------------------------
# Point construction from k value
# ---------------------------------------------------------------------------

def _make_ec_point(
    p: int, q: int, r: int, k: Fraction, inside_only: bool
) -> Optional[RationalPoint]:
    """Construct a RationalPoint from triple (p,q,r) and scale k.

    Applies side-exclusion and optional inside filter.
    Returns None if the point is excluded.
    """
    x = k * Fraction(p, r)
    y = k * Fraction(q, r)

    if x == 0 or y == 0:
        return None
    if x == 1 or y == 1:
        return None
    if inside_only and (x >= 1 or y >= 1):
        return None

    return make_point(x, y)


# ---------------------------------------------------------------------------
# Main EC search
# ---------------------------------------------------------------------------

def ec_search(
    max_m: int = 30,
    max_k_num: int = 200,
    max_k_den: int = 100,
    max_steps: int = 20,
    min_rational: int = 3,
    inside_only: bool = False,
    progress: bool = True,
) -> list[RationalPoint]:
    """Search for rational-distance points using the elliptic-curve method.

    Algorithm:
    1. Generate all primitive Pythagorean triples (p, q, r) up to max_m.
    2. For each triple, find seeds (k, dB, dD) with dA=k, dB, dD all rational
       by brute force over k=a/b with a≤max_k_num, b≤max_k_den.
    3. Convert seeds to rational points on the quartic curve E²=F(t).
    4. Expand the EC orbit using chord-tangent steps (up to max_steps).
    5. For each new k in the orbit, check if the point has min_rational
       rational distances (including dC via the parallelogram law).
    6. Deduplicate by D4 symmetry.

    Returns a list of RationalPoints sorted by denominator.
    """
    try:
        from tqdm import tqdm
        _tqdm = tqdm
    except ImportError:
        def _tqdm(it, **kw):
            return it

    triples = primitive_pythagorean_triples(max_m)

    seen_canonical: set[tuple[Fraction, Fraction]] = set()
    results: list[RationalPoint] = []

    it = _tqdm(triples, desc="EC search", unit="triple", disable=not progress)
    for p, q, r in it:
        seeds_raw = find_seeds_for_triple(p, q, r, max_k_num, max_k_den, inside_only)
        if not seeds_raw:
            continue

        ec = QuarticEC(p, q, r)

        # Convert seeds to quartic curve points (t, E)
        curve_seeds: list[tuple[Fraction, Fraction]] = []
        for k, dB, dD in seeds_raw:
            for t in ec.t_from_k_dB(k, dB):
                E = ec.E_from_t_dD(t, dD)
                if ec.on_curve(t, E):
                    curve_seeds.append((t, E))
                    # Also add the conjugate branch
                    if E != 0:
                        curve_seeds.append((t, -E))

        if not curve_seeds:
            continue

        # Expand the orbit
        k_values_from_orbit = ec.expand_orbit(curve_seeds, max_steps=max_steps)

        # Also add the seed k values themselves
        seed_k_values = [k for k, _, _ in seeds_raw]
        all_k_values = list({k: None for k in seed_k_values + k_values_from_orbit})

        for k in all_k_values:
            pt = _make_ec_point(p, q, r, k, inside_only)
            if pt is None:
                continue
            if pt.rational_count < min_rational:
                continue

            cx, cy = canonical_xy(pt.x, pt.y)
            if (cx, cy) in seen_canonical:
                continue
            seen_canonical.add((cx, cy))
            results.append(pt)

    results.sort(key=lambda pt: pt.denominator)
    return results
