"""Elliptic-curve guided search for rational-distance solutions.

Layer 2 of the search strategy: given the parametric seeds found by
brute force, this module extends them along the rational orbit of the
associated quartic elliptic curve to find additional solutions that
lie outside the brute-force range.

Mathematical background
-----------------------
For a primitive Pythagorean triple (p, q, r) with p²+q²=r², consider
the point P=(x,y) = (kp/r, kq/r).  Then:

    dA = k  (always rational for rational k)
    dB² = k² - 2k(p/r) + 1
    dD² = k² - 2k(q/r) + 1
    dC² = dB² + dD² - dA²  (parallelogram law: dA²+dC²=dB²+dD²)

Parametrize the conic dB²=k²-2kp/r+1 via slope t through (k,dB)=(0,1):

    k(t) = 2(t + p/r) / (1 - t²)
    dB(t) = (1 + t² + 2tp/r) / (1 - t²)

Substituting into dD and letting E = r·dD·(1-t²) gives the quartic:

    E² = F(t)  where
    F(t) = r²t⁴ + 4qrt³ + (2r²+4pq)t² + 4r(2p-q)t + (4p²-4pq+r²)

Rational points on this curve (hyperelliptic genus-1 curve over ℚ) form
a group under the chord-tangent law.  Starting from a *seed* — a rational
point discovered by brute force — new rational points are generated by
applying tangent and secant steps.  Each new rational t yields a new
rational k (and thus a new candidate point), which is then checked for
the full 3- or 4-vertex rationality condition.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import gcd, isqrt
from typing import Any

import numpy as np

from rational_distance.math_utils import primitive_pythagorean_triples, rational_sqrt
from rational_distance.square import RationalPoint, canonical_xy, make_point

# ---------------------------------------------------------------------------
# Vectorized seed-finding helpers
# ---------------------------------------------------------------------------


def _build_coprime_arrays(max_k_num: int, max_k_den: int) -> tuple[np.ndarray, np.ndarray]:
    """Return int64 arrays (a_arr, b_arr) of all coprime pairs a≤max_k_num, b≤max_k_den."""
    pairs = [
        (a, b) for b in range(1, max_k_den + 1) for a in range(1, max_k_num + 1) if gcd(a, b) == 1
    ]
    if not pairs:
        return np.empty(0, dtype=np.int64), np.empty(0, dtype=np.int64)
    a_arr = np.array([a for a, b in pairs], dtype=np.int64)
    b_arr = np.array([b for a, b in pairs], dtype=np.int64)
    return a_arr, b_arr


def _isqrt_arr(t: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Vectorized perfect-square check.  Returns (ok, s) where s = isqrt(t)."""
    s = np.floor(np.sqrt(t.astype(np.float64))).astype(np.int64)
    ok = s * s == t
    s1 = s + 1
    fix = ~ok & (s1 * s1 == t)
    ok |= fix
    s[fix] = s1[fix]
    return ok, s


def _find_seeds_numpy(
    p: int,
    q: int,
    r: int,
    a_arr: np.ndarray,
    b_arr: np.ndarray,
    inside_only: bool = False,
) -> list[tuple[int, int, int, int]]:
    """Vectorized seed finder (numpy).

    Returns list of (a, b, sB, sD) integer tuples where
    k = a/b,  dB = sB / (b*r),  dD = sD / (b*r).
    """
    # Side-exclusion: skip x=1 (a*p == b*r) and y=1 (a*q == b*r)
    mask = ~((a_arr * p == b_arr * r) | (a_arr * q == b_arr * r))
    if inside_only:
        mask &= (a_arr * p < b_arr * r) & (a_arr * q < b_arr * r)
    a = a_arr[mask]
    b = b_arr[mask]
    if len(a) == 0:
        return []

    ar = a * r
    bp = b * p
    bq = b * q

    # dB check: tB = (ar-bp)² + (bq)² must be a perfect square
    tB = (ar - bp) ** 2 + bq**2
    okB, sB = _isqrt_arr(tB)
    if not okB.any():
        return []

    # Early exit: only check dD for rows that passed dB
    a2, b2, sB2 = a[okB], b[okB], sB[okB]
    tD = (a2 * r - b2 * q) ** 2 + (b2 * p) ** 2
    okD, sD = _isqrt_arr(tD)

    results: list[tuple[int, int, int, int]] = []
    for i in okD.nonzero()[0]:
        results.append((int(a2[i]), int(b2[i]), int(sB2[i]), int(sD[i])))
    return results


def _find_seeds_gpu(
    xp,
    p: int,
    q: int,
    r: int,
    a_dev,
    b_dev,
    inside_only: bool = False,
) -> list[tuple[int, int, int, int]]:
    """Vectorized seed finder for GPU (cupy / torch wrapper).

    Computes tB and tD simultaneously on GPU, transfers only the (rare) hits
    back to CPU for exact isqrt verification.  Returns list of (a, b, sB, sD).
    """
    from rational_distance.backend import _xp_cast

    mask = ~((a_dev * p == b_dev * r) | (a_dev * q == b_dev * r))
    if inside_only:
        mask = mask & (a_dev * p < b_dev * r) & (a_dev * q < b_dev * r)
    a = a_dev[mask]
    b = b_dev[mask]
    if len(a) == 0:
        return []

    ar = a * r
    bp = b * p
    bq = b * q

    tB = (ar - bp) ** 2 + bq**2
    tD = (ar - bq) ** 2 + bp**2

    # GPU isqrt: approximate via float64 sqrt; hits are verified precisely on CPU
    sB_f = _xp_cast(xp.floor(xp.sqrt(_xp_cast(tB, xp.float64))), xp.int64)
    sD_f = _xp_cast(xp.floor(xp.sqrt(_xp_cast(tD, xp.float64))), xp.int64)
    okB = (sB_f * sB_f == tB) | ((sB_f + 1) * (sB_f + 1) == tB)
    okD = (sD_f * sD_f == tD) | ((sD_f + 1) * (sD_f + 1) == tD)

    mask2 = okB & okD
    if not xp.any(mask2):
        return []

    idx = xp.where(mask2)[0]

    def _to_cpu(arr):
        sliced = arr[idx]
        if hasattr(sliced, "get"):  # CuPy
            return sliced.get()
        if hasattr(sliced, "cpu"):  # PyTorch tensor
            return sliced.cpu().numpy()
        return np.asarray(sliced)  # NumPy passthrough

    a_hit = _to_cpu(a)
    b_hit = _to_cpu(b)

    # Recompute tB/tD on CPU using Python int arithmetic (exact, no overflow).
    # This avoids trusting potentially-overflowed device values for correctness.
    results: list[tuple[int, int, int, int]] = []
    for i in range(len(a_hit)):
        a_i, b_i = int(a_hit[i]), int(b_hit[i])
        tB_i = (a_i * r - b_i * p) ** 2 + (b_i * q) ** 2
        sB_i = isqrt(tB_i)
        if sB_i * sB_i != tB_i:
            sB_i += 1
            if sB_i * sB_i != tB_i:
                continue
        tD_i = (a_i * r - b_i * q) ** 2 + (b_i * p) ** 2
        sD_i = isqrt(tD_i)
        if sD_i * sD_i != tD_i:
            sD_i += 1
            if sD_i * sD_i != tD_i:
                continue
        results.append((a_i, b_i, sB_i, sD_i))
    return results


@dataclass(frozen=True)
class ECSeedRecord:
    seed_index: int
    a: int
    b: int
    k: Fraction
    dB: Fraction
    dD: Fraction


@dataclass
class ECCurveNodeRecord:
    node_index: int
    t: Fraction
    E: Fraction
    kind: str
    step: int
    seed_index: int | None = None
    active: bool = False


@dataclass(frozen=True)
class ECCurveEdgeRecord:
    child_index: int
    parent_index: int
    relation: str
    position: int = 0


@dataclass(frozen=True)
class ECCandidateRecord:
    candidate_index: int
    source_kind: str
    source_seed_index: int | None
    source_node_index: int | None
    k: Fraction | None
    status: str
    x: Fraction | None = None
    y: Fraction | None = None
    point: RationalPoint | None = None
    canonical_xy: tuple[Fraction, Fraction] | None = None


@dataclass(frozen=True)
class ECSeedBranch:
    seed_index: int
    t: Fraction
    E: Fraction


@dataclass
class ECOrbitTrace:
    nodes: list[ECCurveNodeRecord]
    edges: list[ECCurveEdgeRecord]
    active_node_indices: list[int]
    seed_primary_nodes: dict[int, int]


@dataclass
class ECTripleTrace:
    p: int
    q: int
    r: int
    seeds: list[ECSeedRecord]
    nodes: list[ECCurveNodeRecord]
    edges: list[ECCurveEdgeRecord]
    candidates: list[ECCandidateRecord]

    def accepted_points(self) -> list[RationalPoint]:
        return [candidate.point for candidate in self.candidates if candidate.status == "accepted"]


# ---------------------------------------------------------------------------
# Quartic elliptic curve for one Pythagorean triple
# ---------------------------------------------------------------------------


class QuarticEC:
    """Quartic elliptic curve  E² = F(t)  associated with triple (p, q, r).

    Coefficients (all integers, since p,q,r ∈ ℤ):
        c4 = r²
        c3 = 4qr
        c2 = 2r² + 4pq
        c1 = 4r(2p - q)
        c0 = 4p² - 4pq + r²
    """

    def __init__(self, p: int, q: int, r: int) -> None:
        self.p = p
        self.q = q
        self.r = r
        self.c4 = r * r
        self.c3 = 4 * q * r
        self.c2 = 2 * r * r + 4 * p * q
        self.c1 = 4 * r * (2 * p - q)
        self.c0 = 4 * p * p - 4 * p * q + r * r

    def F(self, t: Fraction) -> Fraction:
        """Evaluate the quartic polynomial F(t)."""
        return self.c4 * t**4 + self.c3 * t**3 + self.c2 * t**2 + self.c1 * t + self.c0

    def on_curve(self, t: Fraction, E: Fraction) -> bool:
        """Return True iff (t, E) satisfies E² = F(t)."""
        return self.F(t) == E * E

    def k_from_t(self, t: Fraction) -> Fraction | None:
        """Convert slope parameter t to scale factor k.

        k(t) = 2(t + p/r) / (1 - t²)

        Returns None when t = ±1 (k = ∞, projective point).
        """
        denom = 1 - t * t
        if denom == 0:
            return None
        return 2 * (t + Fraction(self.p, self.r)) / denom

    def t_from_k_dB(self, k: Fraction, dB: Fraction) -> list[Fraction]:
        """Recover the slope parameter t from (k, dB).

        From the parametrization:  t = (dB·(1-t²) - 1 - t²·...) — but
        the simpler inversion comes from the definition of the slope:
            t = (k - 1 - dB) / k   or   t = (k - 1 + dB) / (-k)
        which simplifies to:
            t = (-1 ± dB) / k  (when k ≠ 0)
        Returns all valid real roots (at most 2).
        """
        if k == 0:
            return []
        return [(-1 + dB) / k, (-1 - dB) / k]

    def E_from_t_dD(self, t: Fraction, dD: Fraction) -> Fraction:
        """Compute E = r·dD·(1-t²) from t and dD."""
        return Fraction(self.r) * dD * (1 - t * t)

    # ------------------------------------------------------------------
    # Chord-tangent arithmetic
    # ------------------------------------------------------------------

    def _tangent_quadratic(self, t0: Fraction, E0: Fraction) -> tuple[Fraction, Fraction, Fraction]:
        """Return (A, B, C) of residual quadratic h after removing double root t0.

        The tangent line Y = λ(t-t0)+E0 meets the quartic in (t0,E0) twice
        plus two more points whose t-values are roots of h(t)=At²+Bt+C.

            λ = F'(t0) / (2·E0)
            A = c4
            B = c3 + 2·c4·t0
            C = c2 - λ² + 2·c3·t0 + 3·c4·t0²
        """
        Fp = 4 * self.c4 * t0**3 + 3 * self.c3 * t0**2 + 2 * self.c2 * t0 + self.c1
        slope = Fp / (2 * E0)
        A = Fraction(self.c4)
        B = Fraction(self.c3) + 2 * A * t0
        C = Fraction(self.c2) - slope**2 + 2 * Fraction(self.c3) * t0 + 3 * A * t0**2
        return A, B, C

    def _secant_quadratic(
        self,
        t1: Fraction,
        E1: Fraction,
        t2: Fraction,
        E2: Fraction,
    ) -> tuple[Fraction, Fraction, Fraction]:
        """Return (A, B, C) of residual quadratic h after removing roots t1, t2.

        The secant line Y = μt+ν meets the quartic in (t1,E1), (t2,E2) plus
        two more points whose t-values are roots of h(t)=At²+Bt+C.

            μ = (E2-E1) / (t2-t1)
            A = c4
            B = c3 + c4·(t1+t2)
            C = c2 - μ² + B·(t1+t2) - c4·t1·t2
        """
        slope = (E2 - E1) / (t2 - t1)
        A = Fraction(self.c4)
        B = Fraction(self.c3) + A * (t1 + t2)
        C = Fraction(self.c2) - slope**2 + B * (t1 + t2) - A * t1 * t2
        return A, B, C

    def _new_t_from_line(
        self,
        A: Fraction,
        B: Fraction,
        C: Fraction,
        slope: Fraction,
        intercept: Fraction,
    ) -> list[tuple[Fraction, Fraction]]:
        """Find rational roots of h(t)=At²+Bt+C and return (t_new, E_new) pairs.

        E_new = slope·t_new + intercept  (from the tangent/secant line).
        Only roots with rational discriminant are returned.
        """
        disc = B * B - 4 * A * C
        sqrt_disc = rational_sqrt(disc)
        if sqrt_disc is None:
            return []
        results = []
        for sign in [1, -1]:
            t_new = (-B + sign * sqrt_disc) / (2 * A)
            E_new = slope * t_new + intercept
            results.append((t_new, E_new))
        return results

    def tangent_points(self, t0: Fraction, E0: Fraction) -> list[tuple[Fraction, Fraction]]:
        """Apply the tangent step at (t0, E0).

        Returns new (t, E) pairs on the quartic distinct from (t0, E0).
        """
        A, B, C = self._tangent_quadratic(t0, E0)
        Fp = 4 * self.c4 * t0**3 + 3 * self.c3 * t0**2 + 2 * self.c2 * t0 + self.c1
        slope = Fp / (2 * E0)
        intercept = E0 - slope * t0
        pts = self._new_t_from_line(A, B, C, slope, intercept)
        return [(t, E) for t, E in pts if t != t0]

    def secant_points(
        self,
        t1: Fraction,
        E1: Fraction,
        t2: Fraction,
        E2: Fraction,
    ) -> list[tuple[Fraction, Fraction]]:
        """Apply the secant step through (t1, E1) and (t2, E2).

        Returns new (t, E) pairs on the quartic distinct from t1 and t2.
        Returns empty list when t1 == t2.
        """
        if t1 == t2:
            return []
        A, B, C = self._secant_quadratic(t1, E1, t2, E2)
        slope = (E2 - E1) / (t2 - t1)
        intercept = E1 - slope * t1
        pts = self._new_t_from_line(A, B, C, slope, intercept)
        return [(t, E) for t, E in pts if t != t1 and t != t2]

    def expand_orbit(
        self,
        seeds: list[tuple[Fraction, Fraction]],
        max_steps: int = 20,
        max_denom: int = 10**18,
    ) -> list[Fraction]:
        """Expand the rational orbit starting from seed points.

        Applies tangent and secant steps up to max_steps iterations.
        Returns a list of rational k values corresponding to found points
        on the quartic, filtered to exclude k=0, k<0, and k=∞.

        Points whose t-denominator exceeds max_denom are skipped to
        prevent runaway fraction growth.
        """
        orbit: dict[Fraction, Fraction] = {}  # t -> E
        for t, E in seeds:
            if abs(t.denominator) <= max_denom:
                orbit[t] = E

        queue = list(orbit.items())
        step = 0

        while queue and step < max_steps:
            step += 1
            new_pts: list[tuple[Fraction, Fraction]] = []

            for t0, E0 in queue:
                # Tangent step
                for t_new, E_new in self.tangent_points(t0, E0):
                    if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                        new_pts.append((t_new, E_new))

            # Secant steps between all pairs in the current frontier
            frontier = list(orbit.items())
            for i in range(len(frontier)):
                for j in range(i + 1, len(frontier)):
                    t1, E1 = frontier[i]
                    t2, E2 = frontier[j]
                    for t_new, E_new in self.secant_points(t1, E1, t2, E2):
                        if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                            new_pts.append((t_new, E_new))
                    # Also try with negated E2 (the other branch of the curve)
                    for t_new, E_new in self.secant_points(t1, E1, t2, -E2):
                        if t_new not in orbit and abs(t_new.denominator) <= max_denom:
                            new_pts.append((t_new, E_new))

            if not new_pts:
                break

            # Deduplicate and add to orbit
            for t_new, E_new in new_pts:
                if t_new not in orbit:
                    orbit[t_new] = E_new
            queue = new_pts

        # Convert t values to k values, filtering out infinite/negative k
        k_values = []
        for t in orbit:
            k = self.k_from_t(t)
            if k is not None and k > 0:
                k_values.append(k)
        return k_values

    def expand_orbit_trace(
        self,
        seed_branches: list[ECSeedBranch],
        max_steps: int = 20,
        max_denom: int = 10**18,
    ) -> ECOrbitTrace:
        """Expand the orbit while keeping node and edge provenance."""

        nodes: list[ECCurveNodeRecord] = []
        edges: list[ECCurveEdgeRecord] = []
        node_lookup: dict[tuple[Fraction, Fraction], int] = {}
        edge_keys: set[tuple[int, int, str, int]] = set()
        seed_primary_nodes: dict[int, int] = {}

        def _kind_rank(kind: str) -> int:
            return {"conjugate_branch": 0, "seed_branch": 1, "orbit": 2}.get(kind, -1)

        def ensure_node(
            t: Fraction,
            E: Fraction,
            kind: str,
            step: int,
            seed_index: int | None = None,
        ) -> int:
            key = (t, E)
            existing = node_lookup.get(key)
            if existing is not None:
                node = nodes[existing]
                if _kind_rank(kind) > _kind_rank(node.kind):
                    node.kind = kind
                if seed_index is not None and node.seed_index is None:
                    node.seed_index = seed_index
                node.step = min(node.step, step)
                return existing

            node_index = len(nodes)
            nodes.append(
                ECCurveNodeRecord(
                    node_index=node_index,
                    t=t,
                    E=E,
                    kind=kind,
                    step=step,
                    seed_index=seed_index,
                )
            )
            node_lookup[key] = node_index
            if seed_index is not None and seed_index not in seed_primary_nodes:
                seed_primary_nodes[seed_index] = node_index
            return node_index

        active_orbit: dict[Fraction, int] = {}
        for branch in seed_branches:
            if abs(branch.t.denominator) > max_denom:
                continue
            node_index = ensure_node(branch.t, branch.E, "seed_branch", 0, branch.seed_index)
            active_orbit[branch.t] = node_index

        queue = list(active_orbit.values())
        step = 0

        while queue and step < max_steps:
            step += 1
            new_active: list[tuple[Fraction, int]] = []
            pending_t: set[Fraction] = set()

            for parent_index in queue:
                parent = nodes[parent_index]
                for t_new, E_new in self.tangent_points(parent.t, parent.E):
                    if abs(t_new.denominator) > max_denom:
                        continue
                    child_index = ensure_node(t_new, E_new, "orbit", step)
                    edge_key = (child_index, parent_index, "tangent", 0)
                    if edge_key not in edge_keys:
                        edge_keys.add(edge_key)
                        edges.append(ECCurveEdgeRecord(child_index, parent_index, "tangent", 0))
                    if t_new not in active_orbit and t_new not in pending_t:
                        pending_t.add(t_new)
                        new_active.append((t_new, child_index))

            frontier = list(active_orbit.values())
            for i in range(len(frontier)):
                for j in range(i + 1, len(frontier)):
                    parent_a = nodes[frontier[i]]
                    parent_b = nodes[frontier[j]]
                    for t_new, E_new in self.secant_points(
                        parent_a.t, parent_a.E, parent_b.t, parent_b.E
                    ):
                        if abs(t_new.denominator) > max_denom:
                            continue
                        child_index = ensure_node(t_new, E_new, "orbit", step)
                        for position, parent_index in enumerate((frontier[i], frontier[j])):
                            edge_key = (child_index, parent_index, "secant", position)
                            if edge_key not in edge_keys:
                                edge_keys.add(edge_key)
                                edges.append(
                                    ECCurveEdgeRecord(
                                        child_index=child_index,
                                        parent_index=parent_index,
                                        relation="secant",
                                        position=position,
                                    )
                                )
                        if t_new not in active_orbit and t_new not in pending_t:
                            pending_t.add(t_new)
                            new_active.append((t_new, child_index))

                    neg_parent_index = ensure_node(
                        parent_b.t,
                        -parent_b.E,
                        "conjugate_branch",
                        parent_b.step,
                        parent_b.seed_index,
                    )
                    for t_new, E_new in self.secant_points(
                        parent_a.t, parent_a.E, parent_b.t, -parent_b.E
                    ):
                        if abs(t_new.denominator) > max_denom:
                            continue
                        child_index = ensure_node(t_new, E_new, "orbit", step)
                        for position, parent_index in enumerate((frontier[i], neg_parent_index)):
                            edge_key = (child_index, parent_index, "secant_neg_branch", position)
                            if edge_key not in edge_keys:
                                edge_keys.add(edge_key)
                                edges.append(
                                    ECCurveEdgeRecord(
                                        child_index=child_index,
                                        parent_index=parent_index,
                                        relation="secant_neg_branch",
                                        position=position,
                                    )
                                )
                        if t_new not in active_orbit and t_new not in pending_t:
                            pending_t.add(t_new)
                            new_active.append((t_new, child_index))

            if not new_active:
                break

            queue = []
            for t_new, child_index in new_active:
                if t_new not in active_orbit:
                    active_orbit[t_new] = child_index
                    queue.append(child_index)

        for node_index in active_orbit.values():
            nodes[node_index].active = True

        return ECOrbitTrace(
            nodes=nodes,
            edges=edges,
            active_node_indices=list(active_orbit.values()),
            seed_primary_nodes=seed_primary_nodes,
        )


# ---------------------------------------------------------------------------
# Seed finder: brute-force search for (k, dB, dD) all rational
# ---------------------------------------------------------------------------

# Largest X such that X² fits in int64 and (X+1)² also fits.
# Ensures each squared term in tB/tD stays within int64 range.
# isqrt((INT64_MAX - 1) // 2) = 2^31 - 1 = 2 147 483 647.
_INT64_SAFE_HALF: int = (1 << 31) - 1


def _seeds_raw_to_fractions(
    raw: list[tuple[int, int, int, int]], r: int
) -> list[tuple[Fraction, Fraction, Fraction]]:
    """Convert (a, b, sB, sD) integer tuples to (k, dB, dD) Fraction triples."""
    seeds = []
    for a, b, sB, sD in raw:
        br = b * r
        seeds.append((Fraction(a, b), Fraction(sB, br), Fraction(sD, br)))
    return seeds


def find_seeds_for_triple(
    p: int,
    q: int,
    r: int,
    max_k_num: int,
    max_k_den: int,
    inside_only: bool = False,
    _a_arr: np.ndarray | None = None,
    _b_arr: np.ndarray | None = None,
) -> list[tuple[Fraction, Fraction, Fraction]]:
    """Find all rational k = a/b such that dB and dD are both rational.

    These are seeds for the quartic elliptic curve associated with (p,q,r).
    Returns a list of (k, dB, dD) Fraction triples.  Points on extended
    sides (x=1 or y=1) are excluded.

    Uses numpy vectorisation when int64 arithmetic is safe for the given r;
    falls back to exact Python-int arithmetic for very large r.
    Pre-built coprime arrays may be passed as _a_arr/_b_arr to avoid
    rebuilding them when calling this function many times in a loop.
    """
    # Int64 safety: tB/tD dominant term ≤ 2*((max_k_num+max_k_den)*r)².
    # Require (max_k_num+max_k_den)*r ≤ _INT64_SAFE_HALF.
    coeff = max_k_num + max_k_den
    safe_r_max = _INT64_SAFE_HALF // coeff if coeff > 0 else 10**18

    if r <= safe_r_max:
        # Fast numpy path
        if _a_arr is None:
            _a_arr, _b_arr = _build_coprime_arrays(max_k_num, max_k_den)
        raw = _find_seeds_numpy(p, q, r, _a_arr, _b_arr, inside_only)
        return _seeds_raw_to_fractions(raw, r)

    # Fallback: exact Python-int arithmetic (no overflow possible)
    seeds: list[tuple[Fraction, Fraction, Fraction]] = []
    for b in range(1, max_k_den + 1):
        for a in range(1, max_k_num + 1):
            if gcd(a, b) != 1:
                continue
            if a * p == b * r or a * q == b * r:
                continue
            if inside_only and (a * p > b * r or a * q > b * r):
                continue
            ar, bp, bq, br = a * r, b * p, b * q, b * r
            tB = (ar - bp) ** 2 + bq * bq
            sB = isqrt(tB)
            if sB * sB != tB:
                s1 = sB + 1
                if s1 * s1 != tB:
                    continue
                sB = s1
            tD = (ar - bq) ** 2 + bp * bp
            sD = isqrt(tD)
            if sD * sD != tD:
                s1 = sD + 1
                if s1 * s1 != tD:
                    continue
                sD = s1
            seeds.append((Fraction(a, b), Fraction(sB, br), Fraction(sD, br)))
    return seeds


# ---------------------------------------------------------------------------
# Point construction from k value
# ---------------------------------------------------------------------------


def _make_ec_point(p: int, q: int, r: int, k: Fraction, inside_only: bool) -> RationalPoint | None:
    """Construct a RationalPoint from triple (p,q,r) and scale k.

    Applies side-exclusion and optional inside filter.
    Returns None if the point is excluded.
    """
    x = k * Fraction(p, r)
    y = k * Fraction(q, r)

    if x == 0 or y == 0:
        return None
    if x == 1 or y == 1:
        return None
    if inside_only and (x >= 1 or y >= 1):
        return None

    return make_point(x, y)


def _point_xy_from_k(p: int, q: int, r: int, k: Fraction) -> tuple[Fraction, Fraction]:
    return k * Fraction(p, r), k * Fraction(q, r)


def _evaluate_candidate(
    p: int,
    q: int,
    r: int,
    k: Fraction | None,
    inside_only: bool,
    min_rational: int,
) -> tuple[
    str,
    Fraction | None,
    Fraction | None,
    RationalPoint | None,
    tuple[Fraction, Fraction] | None,
]:
    if k is None:
        return "infinite_k", None, None, None, None
    if k <= 0:
        return "non_positive_k", None, None, None, None

    x, y = _point_xy_from_k(p, q, r, k)
    if x == 0 or y == 0 or x == 1 or y == 1:
        return "side_filtered", x, y, None, None
    if inside_only and (x >= 1 or y >= 1):
        return "inside_filtered", x, y, None, None

    point = make_point(x, y)
    canonical = canonical_xy(point.x, point.y)
    if point.rational_count < min_rational:
        return "insufficient_rational", x, y, point, canonical
    return "candidate_ok", x, y, point, canonical


# ---------------------------------------------------------------------------
# Main EC search
# ---------------------------------------------------------------------------


def _build_triple_trace(
    p: int,
    q: int,
    r: int,
    seeds_raw: list[tuple[Fraction, Fraction, Fraction]],
    max_steps: int,
    min_rational: int,
    inside_only: bool,
    seen_canonical: set[tuple[Fraction, Fraction]],
) -> ECTripleTrace:
    seed_records = [
        ECSeedRecord(
            seed_index=index,
            a=seed_k.numerator,
            b=seed_k.denominator,
            k=seed_k,
            dB=dB,
            dD=dD,
        )
        for index, (seed_k, dB, dD) in enumerate(seeds_raw)
    ]

    ec = QuarticEC(p, q, r)
    seed_branches: list[ECSeedBranch] = []
    for seed in seed_records:
        for t in ec.t_from_k_dB(seed.k, seed.dB):
            E = ec.E_from_t_dD(t, seed.dD)
            if ec.on_curve(t, E):
                seed_branches.append(ECSeedBranch(seed.seed_index, t, E))
                if E != 0:
                    seed_branches.append(ECSeedBranch(seed.seed_index, t, -E))

    if not seed_branches:
        return ECTripleTrace(p=p, q=q, r=r, seeds=seed_records, nodes=[], edges=[], candidates=[])

    orbit_trace = ec.expand_orbit_trace(seed_branches, max_steps=max_steps)

    seen_k: set[Fraction | None] = set()
    candidates: list[ECCandidateRecord] = []

    def add_candidate(
        source_kind: str,
        source_seed_index: int | None,
        source_node_index: int | None,
        k: Fraction | None,
    ) -> None:
        base_status, x, y, point, canonical = _evaluate_candidate(
            p, q, r, k, inside_only, min_rational
        )
        status = base_status
        if k in seen_k:
            status = "k_duplicate"
        else:
            seen_k.add(k)
            if base_status == "candidate_ok" and canonical is not None:
                if canonical in seen_canonical:
                    status = "d4_duplicate"
                else:
                    status = "accepted"
                    seen_canonical.add(canonical)

        candidates.append(
            ECCandidateRecord(
                candidate_index=len(candidates),
                source_kind=source_kind,
                source_seed_index=source_seed_index,
                source_node_index=source_node_index,
                k=k,
                status=status,
                x=x,
                y=y,
                point=point,
                canonical_xy=canonical,
            )
        )

    for seed in seed_records:
        add_candidate(
            source_kind="seed",
            source_seed_index=seed.seed_index,
            source_node_index=orbit_trace.seed_primary_nodes.get(seed.seed_index),
            k=seed.k,
        )

    for node_index in orbit_trace.active_node_indices:
        node = orbit_trace.nodes[node_index]
        add_candidate(
            source_kind="orbit",
            source_seed_index=None,
            source_node_index=node.node_index,
            k=ec.k_from_t(node.t),
        )

    return ECTripleTrace(
        p=p,
        q=q,
        r=r,
        seeds=seed_records,
        nodes=orbit_trace.nodes,
        edges=orbit_trace.edges,
        candidates=candidates,
    )


def ec_search(
    max_m: int = 30,
    max_k_num: int = 200,
    max_k_den: int = 100,
    max_steps: int = 20,
    min_rational: int = 3,
    inside_only: bool = False,
    progress: bool = True,
    xp=None,
    store: Any | None = None,
) -> list[RationalPoint]:
    """Search for rational-distance points using the elliptic-curve method.

    Algorithm:
    1. Generate all primitive Pythagorean triples (p, q, r) up to max_m.
    2. For each triple, find seeds (k, dB, dD) with dA=k, dB, dD all rational
       by brute force over k=a/b with a≤max_k_num, b≤max_k_den.
    3. Convert seeds to rational points on the quartic curve E²=F(t).
    4. Expand the EC orbit using chord-tangent steps (up to max_steps).
    5. For each new k in the orbit, check if the point has min_rational
       rational distances (including dC via the parallelogram law).
    6. Deduplicate by D4 symmetry.

    Parameters
    ----------
    xp : array backend for GPU acceleration.  Pass the cupy module or a
         PyTorch wrapper (as returned by detect_backend) to use the GPU for
         the seed-finding step.  None (default) uses numpy on CPU.

    Returns a list of RationalPoints sorted by denominator.
    """
    try:
        from tqdm import tqdm

        _tqdm = tqdm
    except ImportError:

        def _tqdm(it, **kw):
            return it

    triples = primitive_pythagorean_triples(max_m)

    # Build coprime arrays once; upload to device if a real GPU backend given.
    _use_gpu = xp is not None and xp is not np
    a_cpu, b_cpu = _build_coprime_arrays(max_k_num, max_k_den)
    if _use_gpu:
        a_dev = xp.array(a_cpu.tolist(), dtype=xp.int64)
        b_dev = xp.array(b_cpu.tolist(), dtype=xp.int64)
    else:
        a_dev = b_dev = None  # not used

    # Int64 safety bound — same logic as in find_seeds_for_triple
    coeff = max_k_num + max_k_den
    safe_r_max = _INT64_SAFE_HALF // coeff if coeff > 0 else 10**18

    results = store.existing_points() if store is not None else []
    seen_canonical: set[tuple[Fraction, Fraction]] = {
        canonical_xy(point.x, point.y) for point in results
    }

    it = _tqdm(triples, desc="EC search", unit="triple", disable=not progress)
    for triple_index, (p, q, r) in enumerate(it):
        if store is not None and (p, q, r) in store.processed_triples:
            continue

        # Seed finding — GPU, numpy, or Python fallback based on safety
        if _use_gpu and r <= safe_r_max:
            raw = _find_seeds_gpu(xp, p, q, r, a_dev, b_dev, inside_only)
            seeds_raw = _seeds_raw_to_fractions(raw, r)
        else:
            seeds_raw = find_seeds_for_triple(
                p,
                q,
                r,
                max_k_num,
                max_k_den,
                inside_only,
                _a_arr=a_cpu,
                _b_arr=b_cpu,
            )

        if not seeds_raw:
            if store is not None:
                store.record_triple(
                    triple_index,
                    ECTripleTrace(p=p, q=q, r=r, seeds=[], nodes=[], edges=[], candidates=[]),
                )
            continue

        if store is not None:
            trace = _build_triple_trace(
                p=p,
                q=q,
                r=r,
                seeds_raw=seeds_raw,
                max_steps=max_steps,
                min_rational=min_rational,
                inside_only=inside_only,
                seen_canonical=seen_canonical,
            )
            store.record_triple(triple_index, trace)
            results.extend(trace.accepted_points())
            continue

        ec = QuarticEC(p, q, r)

        curve_seeds: list[tuple[Fraction, Fraction]] = []
        for k, dB, dD in seeds_raw:
            for t in ec.t_from_k_dB(k, dB):
                E = ec.E_from_t_dD(t, dD)
                if ec.on_curve(t, E):
                    curve_seeds.append((t, E))
                    if E != 0:
                        curve_seeds.append((t, -E))

        if not curve_seeds:
            continue

        k_values_from_orbit = ec.expand_orbit(curve_seeds, max_steps=max_steps)
        seed_k_values = [k for k, _, _ in seeds_raw]
        all_k_values = list(dict.fromkeys(seed_k_values + k_values_from_orbit))

        for k in all_k_values:
            pt = _make_ec_point(p, q, r, k, inside_only)
            if pt is None:
                continue
            if pt.rational_count < min_rational:
                continue

            cx, cy = canonical_xy(pt.x, pt.y)
            if (cx, cy) in seen_canonical:
                continue
            seen_canonical.add((cx, cy))
            results.append(pt)

    results.sort(key=lambda pt: pt.denominator)
    return results
