#!/usr/bin/env python3
"""Turn selected closure-first 3/4 near-misses into square-equation ledgers."""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from math import gcd, isqrt
from pathlib import Path
from typing import Any

EDGES: tuple[tuple[str, str, str], ...] = (
    ("A-N1", "A", "N1"),
    ("B-N1", "B", "N1"),
    ("B-N2", "B", "N2"),
    ("A-N2", "A", "N2"),
)
EDGE_SYMBOLS: dict[str, tuple[str, str, str]] = {
    "A-N1": ("u", "p", "q"),
    "B-N1": ("v", "r", "s"),
    "B-N2": ("w", "x", "y"),
    "A-N2": ("t", "i", "j"),
}
LABEL_ORDER: tuple[str, ...] = ("A", "B", "N1", "N2")


def _nearest_square(value: int) -> tuple[bool, int | None, int, int, int]:
    root = isqrt(value)
    if root * root == value:
        return True, root, root, 0, 0
    lower_delta = value - root * root
    upper_root = root + 1
    upper_delta = upper_root * upper_root - value
    if lower_delta <= upper_delta:
        return False, None, root, lower_delta, lower_delta
    return False, None, upper_root, upper_delta, -upper_delta


def _triple_for(
    left_label: str,
    right_label: str,
    leg1: int,
    leg2: int,
    hypotenuse: int,
) -> dict[str, Any]:
    scale = gcd(gcd(leg1, leg2), hypotenuse)
    primitive = [*sorted([leg1 // scale, leg2 // scale]), hypotenuse // scale]
    euclid = _euclid_parameters(primitive)
    return {
        "leg1": leg1,
        "leg2": leg2,
        "hypotenuse": hypotenuse,
        "primitive": primitive,
        "euclid": euclid,
        "generated_legs": _generated_legs(
            left_label,
            right_label,
            leg1,
            leg2,
            scale,
            euclid,
        ),
        "scale": scale,
    }


def _euclid_parameters(primitive: list[int]) -> dict[str, int]:
    leg_a, leg_b, hypotenuse = primitive
    odd_leg, even_leg = (leg_a, leg_b) if leg_a % 2 else (leg_b, leg_a)
    m = isqrt((hypotenuse + odd_leg) // 2)
    n = isqrt((hypotenuse - odd_leg) // 2)
    if (
        m <= n
        or m * m + n * n != hypotenuse
        or 2 * m * n != even_leg
        or m * m - n * n != odd_leg
    ):
        raise ValueError(f"not a primitive Euclid triple: {primitive}")
    return {"m": m, "n": n, "odd_leg": odd_leg, "even_leg": even_leg}


def _generated_legs(
    left_label: str,
    right_label: str,
    leg1: int,
    leg2: int,
    scale: int,
    euclid: dict[str, int],
) -> dict[str, dict[str, int | str]]:
    return {
        left_label: _generated_leg(leg1, scale, euclid),
        right_label: _generated_leg(leg2, scale, euclid),
    }


def _generated_leg(
    value: int,
    scale: int,
    euclid: dict[str, int],
) -> dict[str, int | str]:
    primitive_value = value // scale
    if primitive_value == euclid["odd_leg"]:
        return {
            "value": value,
            "primitive_value": primitive_value,
            "role": "odd_leg",
            "formula": "scale*(m^2-n^2)",
        }
    if primitive_value == euclid["even_leg"]:
        return {
            "value": value,
            "primitive_value": primitive_value,
            "role": "even_leg",
            "formula": "scale*(2*m*n)",
        }
    raise ValueError(f"leg {value} is not generated by Euclid data {euclid}")


def _edge_summary(name: str, leg1: int, leg2: int) -> dict[str, Any]:
    value = leg1 * leg1 + leg2 * leg2
    is_square, root, nearest_root, nearest_delta, signed_delta = _nearest_square(value)
    out: dict[str, Any] = {
        "leg1": leg1,
        "leg2": leg2,
        "value": value,
        "is_square": is_square,
        "nearest_root": nearest_root,
        "nearest_delta": nearest_delta,
        "signed_delta": signed_delta,
    }
    if root is not None:
        out["root"] = root
        left_label, right_label = name.split("-", 1)
        out["triple"] = _triple_for(left_label, right_label, leg1, leg2, root)
    else:
        out["nearest_square"] = nearest_root * nearest_root
    return out


def _shared_variables(edges: dict[str, dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    seen: dict[str, list[dict[str, Any]]] = {}
    for edge_name, edge in edges.items():
        triple = edge.get("triple")
        if triple is None:
            continue
        for label, leg in triple["generated_legs"].items():
            seen.setdefault(label, []).append(
                {
                    "edge": edge_name,
                    "value": leg["value"],
                    "scale": triple["scale"],
                    "euclid": {
                        "m": triple["euclid"]["m"],
                        "n": triple["euclid"]["n"],
                    },
                    "role": leg["role"],
                    "formula": leg["formula"],
                }
            )
    return {
        label: entries
        for label, entries in seen.items()
        if len(entries) > 1
    }


def _equation_network(
    values: dict[str, int],
    relation: str,
    closure: dict[str, Any],
    missing_edges: list[str],
    shared_variables: dict[str, list[dict[str, Any]]],
    edges: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    return {
        "shared_equations": _shared_equations(shared_variables),
        "closure_equation": {
            "relation": relation,
            "readable": _closure_readable(values, relation, closure),
            "holds": closure["holds"],
        },
        "missing_square_questions": [
            _missing_square_question(edge_name, values, edges[edge_name])
            for edge_name in missing_edges
        ],
    }


def _shared_equations(
    shared_variables: dict[str, list[dict[str, Any]]]
) -> dict[str, dict[str, Any]]:
    equations: dict[str, dict[str, Any]] = {}
    for label, entries in shared_variables.items():
        forms = [_shared_form(entry) for entry in entries]
        value = entries[0]["value"]
        equations[label] = {
            "value": value,
            "forms": forms,
            "readable": f"{label} = {value} = " + " = ".join(
                _form_rhs(form) for form in forms
            ),
        }
    return equations


def _shared_form(entry: dict[str, Any]) -> dict[str, Any]:
    form = {
        "edge": entry["edge"],
        "scale": entry["scale"],
        "m": entry["euclid"]["m"],
        "n": entry["euclid"]["n"],
        "role": entry["role"],
    }
    form["readable"] = f"{entry['value']} = {_form_rhs(form)}"
    return form


def _form_rhs(form: dict[str, Any]) -> str:
    scale = form["scale"]
    m = form["m"]
    n = form["n"]
    if form["role"] == "odd_leg":
        return f"{scale}*({m}^2-{n}^2)"
    return f"{scale}*(2*{m}*{n})"


def _closure_readable(values: dict[str, int], relation: str, closure: dict[str, Any]) -> str:
    if relation == "sum=A+B":
        return f"N1 + N2 = A + B = {closure['target']}"
    if relation == "sum=|A-B|":
        return f"N1 + N2 = |A - B| = {closure['target']}"
    if relation == "diff=A+B":
        return f"|N1 - N2| = A + B = {closure['target']}"
    if relation == "diff=|A-B|":
        return f"|N1 - N2| = |A - B| = {closure['target']}"
    raise ValueError(f"unknown relation: {relation}")


def _missing_square_question(
    edge_name: str,
    values: dict[str, int],
    edge: dict[str, Any],
) -> dict[str, Any]:
    left_label, right_label = edge_name.split("-", 1)
    nearest_root = edge["nearest_root"]
    return {
        "edge": edge_name,
        "readable": (
            f"{left_label}^2 + {right_label}^2 = "
            f"{values[left_label]}^2 + {values[right_label]}^2 = {edge['value']}"
        ),
        "nearest_square": f"{nearest_root}^2 = {edge['nearest_square']}",
        "signed_delta": edge["signed_delta"],
    }


def _template_constraints(
    relation: str,
    missing_edges: list[str],
    shared_variables: dict[str, list[dict[str, Any]]],
    edges: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    return {
        "scope": _template_scope(relation, shared_variables),
        "passed_edge_templates": [
            _passed_edge_template(edge_name, edge)
            for edge_name, edge in edges.items()
            if edge["is_square"]
        ],
        "shared_constraints": _shared_constraints(shared_variables),
        "closure_constraint": _closure_constraint_template(relation),
        "missing_square_constraint": _missing_square_constraint_template(missing_edges),
    }


def _template_scope(
    relation: str,
    shared_variables: dict[str, list[dict[str, Any]]],
) -> str:
    parts = ["focus_bucket", _relation_slug(relation)]
    for label in LABEL_ORDER:
        entries = shared_variables.get(label)
        if not entries:
            continue
        parts.append(label)
        parts.extend(_role_slug(str(entry["role"])) for entry in entries)
    return "_".join(parts)


def _relation_slug(relation: str) -> str:
    return {
        "sum=A+B": "sum_ab",
        "sum=|A-B|": "sum_abs_ab",
        "diff=A+B": "diff_ab",
        "diff=|A-B|": "diff_abs_ab",
    }[relation]


def _role_slug(role: str) -> str:
    return {
        "odd_leg": "odd",
        "even_leg": "even",
    }[role]


def _passed_edge_template(edge_name: str, edge: dict[str, Any]) -> dict[str, Any]:
    scale_symbol, m_symbol, n_symbol = EDGE_SYMBOLS[edge_name]
    triple = edge["triple"]
    return {
        "edge": edge_name,
        "scale_symbol": scale_symbol,
        "m_symbol": m_symbol,
        "n_symbol": n_symbol,
        "assignments": {
            scale_symbol: triple["scale"],
            m_symbol: triple["euclid"]["m"],
            n_symbol: triple["euclid"]["n"],
        },
        "constraints": [
            _leg_constraint(label, leg, scale_symbol, m_symbol, n_symbol)
            for label, leg in triple["generated_legs"].items()
        ],
    }


def _leg_constraint(
    label: str,
    leg: dict[str, int | str],
    scale_symbol: str,
    m_symbol: str,
    n_symbol: str,
) -> str:
    return f"{label} = {_role_template_rhs(str(leg['role']), scale_symbol, m_symbol, n_symbol)}"


def _role_template_rhs(
    role: str,
    scale_symbol: str,
    m_symbol: str,
    n_symbol: str,
) -> str:
    if role == "odd_leg":
        return f"{scale_symbol}*({m_symbol}^2-{n_symbol}^2)"
    return f"{scale_symbol}*(2*{m_symbol}*{n_symbol})"


def _shared_constraints(shared_variables: dict[str, list[dict[str, Any]]]) -> list[str]:
    constraints: list[str] = []
    for label in LABEL_ORDER:
        entries = shared_variables.get(label)
        if not entries:
            continue
        constraints.append(" = ".join(_shared_template_rhs(entry) for entry in entries))
    return constraints


def _shared_template_rhs(entry: dict[str, Any]) -> str:
    scale_symbol, m_symbol, n_symbol = EDGE_SYMBOLS[str(entry["edge"])]
    return _role_template_rhs(str(entry["role"]), scale_symbol, m_symbol, n_symbol)


def _closure_constraint_template(relation: str) -> str:
    if relation == "sum=A+B":
        return "N1 + N2 = A + B"
    if relation == "sum=|A-B|":
        return "N1 + N2 = |A - B|"
    if relation == "diff=A+B":
        return "|N1 - N2| = A + B"
    if relation == "diff=|A-B|":
        return "|N1 - N2| = |A - B|"
    raise ValueError(f"unknown relation: {relation}")


def _missing_square_constraint_template(missing_edges: list[str]) -> str:
    if len(missing_edges) != 1:
        return " and ".join(_missing_edge_square_template(edge_name) for edge_name in missing_edges)
    return _missing_edge_square_template(missing_edges[0])


def _missing_edge_square_template(edge_name: str) -> str:
    left_label, right_label = edge_name.split("-", 1)
    return f"{left_label}^2 + {right_label}^2 = square?"


def _closure_left(a: int, b: int, n1: int, n2: int, relation: str) -> tuple[int, int]:
    if relation == "sum=A+B":
        return n1 + n2, a + b
    if relation == "sum=|A-B|":
        return n1 + n2, abs(a - b)
    if relation == "diff=A+B":
        return abs(n1 - n2), a + b
    if relation == "diff=|A-B|":
        return abs(n1 - n2), abs(a - b)
    raise ValueError(f"unknown relation: {relation}")


def equationize_sample(a: int, b: int, n1: int, n2: int, relation: str) -> dict[str, Any]:
    values = {"A": a, "B": b, "N1": n1, "N2": n2}
    edges = {
        name: _edge_summary(name, values[left], values[right])
        for name, left, right in EDGES
    }
    missing_edges = [name for name, edge in edges.items() if not edge["is_square"]]
    left, target = _closure_left(a, b, n1, n2, relation)
    closure = {
        "relation": relation,
        "left": left,
        "target": target,
        "holds": left == target,
    }
    shared_variables = _shared_variables(edges)
    return {
        "A": a,
        "B": b,
        "N1": n1,
        "N2": n2,
        "relation": relation,
        "closure": closure,
        "square_count": len(edges) - len(missing_edges),
        "missing_edges": missing_edges,
        "shared_variables": shared_variables,
        "equation_network": _equation_network(
            values,
            relation,
            closure,
            missing_edges,
            shared_variables,
            edges,
        ),
        "template_constraints": _template_constraints(
            relation,
            missing_edges,
            shared_variables,
            edges,
        ),
        "edges": edges,
    }


def _parse_sample(text: str) -> tuple[int, int, int, int, str]:
    parts = text.split(",", 4)
    if len(parts) != 5:
        raise ValueError("sample must be A,B,N1,N2,relation")
    a, b, n1, n2 = (int(part) for part in parts[:4])
    return a, b, n1, n2, parts[4]


def build_payload(samples: list[tuple[int, int, int, int, str]]) -> dict[str, Any]:
    return {
        "sample_count": len(samples),
        "samples": [equationize_sample(*sample) for sample in samples],
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sample",
        action="append",
        default=[],
        help="sample as A,B,N1,N2,relation; may be passed multiple times",
    )
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    samples = [_parse_sample(text) for text in args.sample]
    if not samples:
        raise ValueError("pass at least one --sample")
    payload = build_payload(samples)
    if args.out is None:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
