#!/usr/bin/env python3
"""Plot D4-distinct closure-first 3/4 near-miss points.

Input JSON must be generated by ``closure_first_three_square_search.py`` with
``--include-d4-points``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_d4_point_records(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    records = payload.get("d4_point_records")
    if not isinstance(records, list) or not records:
        raise ValueError(
            f"{path} has no d4_point_records; rerun the search with --include-d4-points"
        )
    return records


def render_d4_point_plot(
    records: list[dict[str, Any]],
    out: Path,
    *,
    title_suffix: str = "",
) -> None:
    import matplotlib  # type: ignore[import-not-found]
    import numpy as np
    from matplotlib.colors import LogNorm  # type: ignore[import-not-found]
    from matplotlib.patches import Rectangle  # type: ignore[import-not-found]

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]

    xs = np.array([record["x_float"] for record in records], dtype=float)
    ys = np.array([record["y_float"] for record in records], dtype=float)
    deltas = np.array([record["best_failed_nearest_delta"] for record in records], dtype=float)
    raw_counts = np.array([record["raw_count"] for record in records], dtype=float)
    sizes = 22 + 15 * np.log1p(raw_counts)

    fig, axes = plt.subplots(1, 2, figsize=(16, 7.6), constrained_layout=True)
    fig.patch.set_facecolor("#fbfaf6")
    norm = LogNorm(vmin=max(1, float(deltas.min())), vmax=float(deltas.max()))

    for ax, title in zip(
        axes,
        [
            "All D4-canonical representatives (symlog axes)",
            "Zoom near the square: -2.2 <= x,y <= 1.05",
        ],
        strict=True,
    ):
        ax.set_facecolor("#fffdf8")
        ax.add_patch(
            Rectangle((0, 0), 1, 1, fill=False, edgecolor="#1f2933", linewidth=2.0, linestyle="--")
        )
        ax.axhline(0, color="#9aa5b1", linewidth=0.8)
        ax.axvline(0, color="#9aa5b1", linewidth=0.8)
        ax.axhline(1, color="#cbd2d9", linewidth=0.8)
        ax.axvline(1, color="#cbd2d9", linewidth=0.8)
        ax.plot([-80, 2], [-80, 2], color="#d64545", linewidth=0.8, alpha=0.35, label="x=y")
        scatter = ax.scatter(
            xs,
            ys,
            c=deltas,
            s=sizes,
            cmap="viridis_r",
            norm=norm,
            alpha=0.78,
            edgecolors="#102a43",
            linewidths=0.35,
        )
        small = deltas <= 10
        ax.scatter(
            xs[small],
            ys[small],
            s=sizes[small] + 120,
            facecolors="none",
            edgecolors="#d92323",
            linewidths=1.6,
            label="delta <= 10",
        )
        ax.set_title(title, fontsize=13, pad=10)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.grid(color="#d9e2ec", linewidth=0.6, alpha=0.65)
        ax.set_aspect("equal", adjustable="box")

    axes[0].set_xscale("symlog", linthresh=1)
    axes[0].set_yscale("symlog", linthresh=1)
    axes[0].set_xlim(-90, 1.2)
    axes[0].set_ylim(-45, 1.2)
    axes[1].set_xlim(-2.2, 1.05)
    axes[1].set_ylim(-2.2, 1.05)

    for record in records:
        if record["best_failed_nearest_delta"] == 1:
            x = record["x_float"]
            y = record["y_float"]
            axes[1].annotate(
                "delta=1",
                xy=(x, y),
                xytext=(x + 0.08, y + 0.14),
                arrowprops={"arrowstyle": "->", "color": "#d92323", "lw": 1.2},
                color="#b42318",
                fontsize=10,
                weight="bold",
            )
            axes[0].annotate("delta=1", xy=(x, y), xytext=(0.05, -0.95), color="#b42318")

    handles, labels = axes[1].get_legend_handles_labels()
    axes[1].legend(handles, labels, loc="lower right", frameon=True, facecolor="white")

    cbar = fig.colorbar(scatter, ax=axes, shrink=0.82, pad=0.018)
    cbar.set_label("best failed nearest-square delta (log color)")
    fig.suptitle(
        f"Closure-first 3/4 near-misses: {len(records)} D4-distinct point orbits{title_suffix}\n"
        "marker size = raw records merged into orbit",
        fontsize=15,
        weight="bold",
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=220, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    input_path: Path = args.input
    out = args.out or input_path.with_suffix(".png")
    records = load_d4_point_records(input_path)
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    title_suffix = (
        f"\nmax_leg={payload.get('max_leg')}, diff_tail={payload.get('diff_tail')}"
        if "max_leg" in payload and "diff_tail" in payload
        else ""
    )
    render_d4_point_plot(records, out, title_suffix=title_suffix)
    inside = sum(0 <= record["x_float"] <= 1 and 0 <= record["y_float"] <= 1 for record in records)
    print(f"wrote {out}")
    print(f"records={len(records)} inside_unit_square={inside}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
